# Generated by Django 3.2.6 on 2024-12-05 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='pagado',
            field=models.BooleanField(default=False),
        ),
    ]
